server:
  port: 9000


spring:
  devtools:
    livereload:
      enabled: true
    thymeleaf:
      cache: false
    restart:
      enabled: true

  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/docs?serverTimezone=Asia/Seoul
    username: root
    password: 1234

  jpa:
    hibernate:
      ddl-auto: update
      format_sql: true
      show_sql: true
    generate-ddl: false
    show-sql: true
    database: mysql
    database-platform: org.hibernate.dialect.MySQLDialect

thymeleaf:
  prefix: /templates/
  check-template-location: true
  suffix: .html
  mode: HTML5
  cache: false
  order: 0
